version: '3.8'

services:
  db:
    image: postgres:15.1
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  
  nginx:
    image: nginx:1.17.10-alpine
    container_name: nginx
    depends_on:
      - client
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  client:
    image: client
    container_name: client
    build:
      context: client
    ports:
      - 3000:3000

  # server:
  #   image: server
  #   containter_name: server
  #   build:
  #     context: ./server-go
  #   depends_on:
  #     - db
  #   ports:
  #     - 8001:8001

volumes:
  db:
    driver: local
