version: '3.8'

services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  
  nginx-router:
    image: nginx:1.17.10-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  client:
    image: client
    container_name: client
    build:
      context: client
    ports:
      - 3000:3000

  # server:
  #   image: web-server
  #   containter_name: web_server
  #   build:
  #     context: ./server-go/Dockerfile
  #   ports:
  #     - 8001:8001

volumes:
  db:
    driver: local
